const PROJECT_NAME = 'Raio do Bem';
const PROJECT_IDENTIFY = 'e-vou';
const USER_TOKEN_NAME = 'EVOUUSERTOKEN';
const USER_REFRESH_NAME = 'EVOUUSERREFRESH';

export default { PROJECT_IDENTIFY, PROJECT_NAME, USER_TOKEN_NAME, USER_REFRESH_NAME };
