name: .NET Core

on:
  push:
    paths-ignore:
    - '**.md'
    branches:
    - master
    - develop
    - release/*
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
      working-directory: api
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: api
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: api
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        login-server: registry.lennon.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
