name: .NET Core

on:
  push:
    paths-ignore:
    - '**.md'
    branches:
    - feature/*
    - release/*
    - hotfix/*
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
      working-directory: api
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: api
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: api
    - name: Publish
      run: dotnet publish --configuration Release --no-restore --output out
      working-directory: api
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        login-server: registry.lennon.cloud
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Docker Build
      run: |
        docker build . -t registry.lennon.cloud/edwardjenner/api:${{ github.sha }}
        docker tag registry.lennon.cloud/edwardjenner/api:${{ github.sha }} registry.lennon.cloud/edwardjenner/api:latest
        docker push registry.lennon.cloud/edwardjenner/api:${{ github.sha }}
        docker push registry.lennon.cloud/edwardjenner/api:latest
      working-directory: api
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_ADDRESS }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}
        script: |
          chmod +x ./restart_api.sh
          ./restart_api.sh
