name: Node.js CI

on:
  push:
    paths-ignore:
    - '**.md'
    branches:
    - feature/*
    - release/*
    - hotfix/*
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: front
    - run: npm run build --if-present
      working-directory: front
    - run: npm test
      env:
        CI: true
      working-directory: front
